name: demo-workflow

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      -  name: Cache Node.js modules
         id: cache-node-modules
         uses: actions/cache@v3
         with:
             path: ~/.npm
             key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
             restore-keys: |
              ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Specify your AWS region

      - name: Install AWS CDK
        run: npm install -g aws-cdk
      - name: Deploy CDK stack
        run: cdk bootstrap --require-approval never
      - name: Deploy CDK stack
        run: cdk deploy --require-approval never